//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivanov_Slitels_college.View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public Special()
        {
            this.Group = new HashSet<Group>();
        }
    
        public int Id_Special { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
    }
}
